# Generated by Django 3.0.7 on 2021-08-26 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('categoria', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Zonas',
            },
        ),
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.IntegerField(choices=[(1, 1), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (60, 60), (70, 70)])),
                ('precio', models.FloatField(null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Proveedores')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Zonas')),
            ],
            options={
                'verbose_name_plural': 'Tarifas',
            },
        ),
        migrations.CreateModel(
            name='Distancias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
                ('ciudad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad1', to='pages.Ciudades')),
                ('ciudad2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad2', to='pages.Ciudades')),
            ],
            options={
                'verbose_name_plural': 'Distancias',
            },
        ),
    ]
