# Generated by Django 3.0.7 on 2021-08-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('categoria', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Distancias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Zonas')),
                ('ciudad1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad1', to='pages.Ciudades')),
                ('ciudad2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad2', to='pages.Ciudades')),
            ],
        ),
    ]
