# Generated by Django 3.0.7 on 2021-08-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_distancias_zonas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancias',
            name='categoria',
        ),
    ]
