# Generated by Django 3.0.7 on 2021-08-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_proveedores_tarifas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifas',
            name='nombre',
        ),
    ]
