# Generated by Django 3.0.7 on 2021-08-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_tarifas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifas',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
