# Generated by Django 3.0.7 on 2021-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_tarifas_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='kg',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')]),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
