# Generated by Django 3.0.7 on 2021-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210825_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='kg',
            field=models.IntegerField(choices=[('1', '1'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('60', '60'), ('70', '70')]),
        ),
    ]
